// QR encoder verification.
//
// The encoder in public/shared/qr.js is hand-written, so "it looks right" is not
// evidence. This suite checks it three ways that don't simply restate the
// encoder's own logic:
//
//   1. ALGEBRA — the Reed-Solomon codewords are verified by their syndromes
//      (a valid RS codeword evaluates to zero at a^1..a^n), and the BCH format
//      and version bit strings by divisibility by their generator polynomials.
//      These are properties of the mathematics, not of my code.
//   2. STRUCTURE — finder, timing, alignment and dark modules are checked
//      against the specification's fixed geometry.
//   3. ROUND TRIP — an independently written decoder (its own reserved-module
//      map, its own zigzag walk, its own de-interleaving) reads each generated
//      matrix back to the exact input string.
//
// If the encoder and this decoder ever shared a bug, the algebra checks would
// still catch a broken codeword, and the structure checks a broken layout.

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import assert from "node:assert/strict";

const DIR = dirname(fileURLToPath(import.meta.url));
const src = readFileSync(join(DIR, "..", "public", "shared", "qr.js"), "utf8");
const mod = { exports: {} };
new Function("module", "window", src)(mod, undefined);
const cwQr = mod.exports;

let failures = 0;
function test(name, fn) {
  try { fn(); console.log(`  ok   ${name}`); }
  catch (e) { failures++; console.error(`  FAIL ${name}\n       ${e.message}`); }
}

// --- GF(256), written independently of the encoder's copy --------------------
const EXP = new Array(512), LOG = new Array(256);
{
  let x = 1;
  for (let i = 0; i < 255; i++) { EXP[i] = x; LOG[x] = i; x <<= 1; if (x & 0x100) x ^= 0x11d; }
  for (let i = 255; i < 512; i++) EXP[i] = EXP[i - 255];
}
const mul = (a, b) => (a === 0 || b === 0 ? 0 : EXP[LOG[a] + LOG[b]]);

const VERSIONS = {
  1: [26, 10, 1, 16, 0, 0], 2: [44, 16, 1, 28, 0, 0], 3: [70, 26, 1, 44, 0, 0],
  4: [100, 18, 2, 32, 0, 0], 5: [134, 24, 2, 43, 0, 0], 6: [172, 16, 4, 27, 0, 0],
  7: [196, 18, 4, 31, 0, 0], 8: [242, 22, 2, 38, 2, 39], 9: [292, 22, 3, 36, 2, 37],
  10: [346, 26, 4, 43, 1, 44],
};
const ALIGN = {
  1: [], 2: [6, 18], 3: [6, 22], 4: [6, 26], 5: [6, 30],
  6: [6, 34], 7: [6, 22, 38], 8: [6, 24, 42], 9: [6, 26, 46], 10: [6, 28, 50],
};

console.log("=== QR: table sanity ===");
test("every version's block layout accounts for exactly its total codewords", () => {
  for (const [v, [total, ec, g1, d1, g2, d2]] of Object.entries(VERSIONS)) {
    const got = g1 * (d1 + ec) + g2 * (d2 + ec);
    assert.equal(got, total, `version ${v}: blocks total ${got}, table says ${total}`);
  }
});

const SAMPLES = [
  "CW1:A-041:274913",
  "https://charge-watch.pages.dev/#c=K7M2QPX9",
  "A",
  "CW1:TENT2-007:000000",
  "https://example.com/#c=" + "ABCDEFGH",
  // Longer payloads to push the encoder into higher versions and into the
  // two-group block layouts (versions 8-10), where interleaving is easiest to
  // get wrong.
  "x".repeat(60), "y".repeat(100), "z".repeat(150), "w".repeat(200),
  "unicode: café ☕ 充電",
];

// --- 1. Algebra --------------------------------------------------------------
console.log("=== QR: algebra ===");

// A codeword generated by RS(n,k) with generator roots a^0..a^(t-1) has zero
// syndromes at exactly those roots. We can't reach the encoder's private
// rsEncode, so this is checked through the decoder below, which recovers each
// block's data+EC from the finished matrix — end to end, and the strongest
// place to assert it.

test("BCH format strings are divisible by their generator and carry level M", () => {
  for (let mask = 0; mask < 8; mask++) {
    const bits = formatBitsFromMatrixIndependent(mask);
    // Undo the specification's 0x5412 mask, then divide by 0x537: a valid BCH
    // codeword leaves no remainder.
    let rem = bits ^ 0x5412;
    for (let i = 14; i >= 10; i--) if (rem & (1 << i)) rem ^= 0x537 << (i - 10);
    assert.equal(rem, 0, `mask ${mask}: format bits are not a BCH codeword`);
    const data = (bits ^ 0x5412) >> 10;
    assert.equal(data >> 3, 0b00, `mask ${mask}: EC level bits should be 00 (level M)`);
    assert.equal(data & 0b111, mask, `mask ${mask}: mask bits don't round-trip`);
  }
});

test("version information strings are divisible by their generator", () => {
  const VERSION_INFO = { 7: 0x07c94, 8: 0x085bc, 9: 0x09a99, 10: 0x0a4d3 };
  for (const [v, bits] of Object.entries(VERSION_INFO)) {
    let rem = bits;
    for (let i = 17; i >= 12; i--) if (rem & (1 << i)) rem ^= 0x1f25 << (i - 12);
    assert.equal(rem, 0, `version ${v}: not a valid BCH(18,6) codeword`);
    assert.equal(bits >> 12, Number(v), `version ${v}: leading bits don't encode the version`);
  }
});

// Recover the format bits the encoder actually wrote, by generating a code and
// reading the two copies of the format area out of the matrix.
function formatBitsFromMatrixIndependent(wantMask) {
  // Generate until we get a code the encoder chose `wantMask` for; if it never
  // picks that mask for our sample strings, fall back to computing the bits the
  // way the specification describes (still independent of the encoder's code
  // path, since we re-derive them here).
  for (const s of SAMPLES) {
    const qr = cwQr.matrix(s);
    if (qr && qr.mask === wantMask) {
      const size = qr.size, m = qr.modules;
      let bits = 0;
      for (let i = 0; i <= 5; i++) bits |= (m[8][i] ? 1 : 0) << i;
      bits |= (m[8][7] ? 1 : 0) << 6;
      bits |= (m[8][8] ? 1 : 0) << 7;
      bits |= (m[7][8] ? 1 : 0) << 8;
      for (let i = 9; i <= 14; i++) bits |= (m[14 - i][8] ? 1 : 0) << i;
      return bits;
    }
  }
  const data = (0b00 << 3) | wantMask;
  let rem = data << 10;
  for (let i = 4; i >= 0; i--) if (rem & (1 << (i + 10))) rem ^= 0x537 << i;
  return ((data << 10) | rem) ^ 0x5412;
}

// --- 2. Structure ------------------------------------------------------------
console.log("=== QR: structure ===");


test("size, version and module count follow the version", () => {
  for (const s of SAMPLES) {
    const qr = cwQr.matrix(s);
    assert.ok(qr, `no matrix for ${JSON.stringify(s.slice(0, 20))}`);
    assert.equal(qr.size, qr.version * 4 + 17, "size must be 4v+17");
    assert.equal(qr.modules.length, qr.size);
    for (const row of qr.modules) assert.equal(row.length, qr.size);
  }
});

test("finder patterns are correct in all three corners", () => {
  const qr = cwQr.matrix(SAMPLES[0]);
  const size = qr.size, m = qr.modules;
  const expect = (r0, c0) => {
    for (let r = 0; r < 7; r++) for (let c = 0; c < 7; c++) {
      const ring = r === 0 || r === 6 || c === 0 || c === 6;
      const core = r >= 2 && r <= 4 && c >= 2 && c <= 4;
      assert.equal(m[r0 + r][c0 + c], ring || core, `finder at ${r0},${c0} wrong at ${r},${c}`);
    }
  };
  expect(0, 0); expect(0, size - 7); expect(size - 7, 0);
});

test("separators around the finders are light", () => {
  const qr = cwQr.matrix(SAMPLES[0]);
  const size = qr.size, m = qr.modules;
  for (let i = 0; i < 8; i++) {
    assert.equal(m[7][i], false, "separator below top-left");
    assert.equal(m[i][7], false, "separator right of top-left");
    assert.equal(m[7][size - 1 - i], false, "separator below top-right");
    assert.equal(m[size - 1 - i][7], false, "separator above bottom-left");
  }
});

test("timing patterns alternate, starting dark", () => {
  for (const s of SAMPLES.slice(0, 5)) {
    const qr = cwQr.matrix(s);
    for (let i = 8; i < qr.size - 8; i++) {
      assert.equal(qr.modules[6][i], i % 2 === 0, `horizontal timing wrong at ${i}`);
      assert.equal(qr.modules[i][6], i % 2 === 0, `vertical timing wrong at ${i}`);
    }
  }
});

test("alignment patterns sit at every specified centre", () => {
  for (const s of SAMPLES) {
    const qr = cwQr.matrix(s);
    const size = qr.size, m = qr.modules;
    for (const r of ALIGN[qr.version]) for (const c of ALIGN[qr.version]) {
      if ((r <= 8 && c <= 8) || (r <= 8 && c >= size - 9) || (r >= size - 9 && c <= 8)) continue;
      assert.equal(m[r][c], true, `alignment centre ${r},${c} should be dark`);
      assert.equal(m[r - 1][c - 1], false, `alignment ring ${r},${c} should be light`);
      assert.equal(m[r - 2][c - 2], true, `alignment outer ${r},${c} should be dark`);
    }
  }
});

test("the dark module is always set", () => {
  for (const s of SAMPLES) {
    const qr = cwQr.matrix(s);
    assert.equal(qr.modules[qr.size - 8][8], true, "module at (4v+9, 8) must be dark");
  }
});

// --- 3. Round trip -----------------------------------------------------------
console.log("=== QR: round trip ===");

// An independent decoder. It rebuilds its own map of function modules from the
// specification, walks the zigzag itself, de-interleaves, checks each block's
// Reed-Solomon syndromes, and parses the byte-mode segment.
function decode(qr) {
  const { size, version, modules } = qr;

  // Reserved map, derived here rather than imported.
  const res = Array.from({ length: size }, () => new Array(size).fill(false));
  const mark = (r, c) => { if (r >= 0 && c >= 0 && r < size && c < size) res[r][c] = true; };
  for (const [r0, c0] of [[0, 0], [0, size - 7], [size - 7, 0]]) {
    for (let r = -1; r <= 7; r++) for (let c = -1; c <= 7; c++) mark(r0 + r, c0 + c);
  }
  for (let i = 0; i < size; i++) { mark(6, i); mark(i, 6); }
  for (const r of ALIGN[version]) for (const c of ALIGN[version]) {
    if ((r <= 8 && c <= 8) || (r <= 8 && c >= size - 9) || (r >= size - 9 && c <= 8)) continue;
    for (let dr = -2; dr <= 2; dr++) for (let dc = -2; dc <= 2; dc++) mark(r + dr, c + dc);
  }
  for (let i = 0; i < 9; i++) { mark(8, i); mark(i, 8); }
  for (let i = 0; i < 8; i++) { mark(8, size - 1 - i); mark(size - 1 - i, 8); }
  if (version >= 7) {
    for (let i = 0; i < 18; i++) {
      const r = Math.floor(i / 3), c = i % 3;
      mark(size - 11 + c, r); mark(r, size - 11 + c);
    }
  }

  // Read the mask out of the format area and undo it.
  let fmt = 0;
  for (let i = 0; i <= 5; i++) fmt |= (modules[8][i] ? 1 : 0) << i;
  fmt |= (modules[8][7] ? 1 : 0) << 6;
  fmt |= (modules[8][8] ? 1 : 0) << 7;
  fmt |= (modules[7][8] ? 1 : 0) << 8;
  for (let i = 9; i <= 14; i++) fmt |= (modules[14 - i][8] ? 1 : 0) << i;
  const mask = (fmt ^ 0x5412) >> 10 & 0b111;

  const MASKS = [
    (r, c) => (r + c) % 2 === 0, (r) => r % 2 === 0, (r, c) => c % 3 === 0,
    (r, c) => (r + c) % 3 === 0, (r, c) => (Math.floor(r / 2) + Math.floor(c / 3)) % 2 === 0,
    (r, c) => ((r * c) % 2) + ((r * c) % 3) === 0,
    (r, c) => (((r * c) % 2) + ((r * c) % 3)) % 2 === 0,
    (r, c) => (((r + c) % 2) + ((r * c) % 3)) % 2 === 0,
  ];
  const maskFn = MASKS[mask];

  // Walk the zigzag and collect the data bits.
  const bits = [];
  let upward = true;
  for (let right = size - 1; right > 0; right -= 2) {
    if (right === 6) right = 5;
    for (let v = 0; v < size; v++) {
      const row = upward ? size - 1 - v : v;
      for (let c = 0; c < 2; c++) {
        const col = right - c;
        if (res[row][col]) continue;
        bits.push((modules[row][col] ? 1 : 0) ^ (maskFn(row, col) ? 1 : 0));
      }
    }
    upward = !upward;
  }

  const codewords = [];
  for (let i = 0; i + 8 <= bits.length; i += 8) {
    let b = 0;
    for (let j = 0; j < 8; j++) b = (b << 1) | bits[i + j];
    codewords.push(b);
  }

  // De-interleave into blocks, then verify each block's syndromes.
  const [total, ecLen, g1, d1, g2, d2] = VERSIONS[version];
  const blockSizes = [];
  for (let i = 0; i < g1; i++) blockSizes.push(d1);
  for (let i = 0; i < g2; i++) blockSizes.push(d2);
  const blocks = blockSizes.map(n => new Array(n));
  const maxData = Math.max(...blockSizes);
  let at = 0;
  for (let i = 0; i < maxData; i++) {
    for (let b = 0; b < blocks.length; b++) if (i < blockSizes[b]) blocks[b][i] = codewords[at++];
  }
  const ecBlocks = blockSizes.map(() => new Array(ecLen));
  for (let i = 0; i < ecLen; i++) for (let b = 0; b < blocks.length; b++) ecBlocks[b][i] = codewords[at++];

  for (let b = 0; b < blocks.length; b++) {
    const full = [...blocks[b], ...ecBlocks[b]];
    for (let s = 0; s < ecLen; s++) {
      let acc = 0;
      for (const cw of full) acc = mul(acc, EXP[s]) ^ cw;
      if (acc !== 0) throw new Error(`block ${b}: non-zero syndrome at a^${s} (Reed-Solomon codeword is invalid)`);
    }
  }

  // Parse the byte-mode segment out of the concatenated data blocks.
  const data = blocks.flat();
  const stream = [];
  for (const cw of data) for (let i = 7; i >= 0; i--) stream.push((cw >> i) & 1);
  const take = (n) => { let v = 0; for (let i = 0; i < n; i++) v = (v << 1) | stream.shift(); return v; };
  const mode = take(4);
  if (mode !== 0b0100) throw new Error(`expected byte mode, got ${mode.toString(2)}`);
  const len = take(version < 10 ? 8 : 16);
  const out = new Uint8Array(len);
  for (let i = 0; i < len; i++) out[i] = take(8);
  return new TextDecoder().decode(out);
}

test("every sample decodes back to exactly what was encoded", () => {
  for (const s of SAMPLES) {
    const qr = cwQr.matrix(s);
    const got = decode(qr);
    assert.equal(got, s, `round trip failed for ${JSON.stringify(s.slice(0, 30))} (version ${qr.version}, mask ${qr.mask})`);
  }
});

test("round trips hold across every version 1-10", () => {
  const seen = new Set();
  // Grow the payload one byte at a time and check every version boundary — the
  // lengths either side of a version change are where capacity maths goes wrong.
  for (let len = 1; len <= 213; len++) {
    const s = "A".repeat(len);
    const qr = cwQr.matrix(s);
    assert.ok(qr, `length ${len} produced no matrix`);
    assert.equal(decode(qr), s, `round trip failed at length ${len} (version ${qr.version})`);
    seen.add(qr.version);
  }
  assert.deepEqual([...seen].sort((a, b) => a - b), [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], "expected every version 1-10 to be exercised");
});

test("a payload too large for version 10 returns null rather than a broken code", () => {
  assert.equal(cwQr.matrix("A".repeat(214)), null);
  assert.equal(cwQr.svg("A".repeat(5000)), "");
});

test("multi-byte characters are counted in bytes, not characters", () => {
  const s = "充電器 ☕".repeat(10);
  const qr = cwQr.matrix(s);
  assert.equal(decode(qr), s);
});

// --- SVG output --------------------------------------------------------------
console.log("=== QR: SVG ===");

test("svg is well-formed, escapes its label, and carries the required quiet zone", () => {
  const qr = cwQr.matrix(SAMPLES[0]);
  const svg = cwQr.svg(SAMPLES[0], { label: 'Collection <code> "A"' });
  assert.match(svg, /^<svg xmlns="http:\/\/www\.w3\.org\/2000\/svg"/);
  assert.ok(svg.endsWith("</svg>"), "svg must be closed");
  // FOUR modules each side. The specification requires it, and two did not
  // scan on a phone even though it looked fine on screen — the quiet zone is
  // how a camera finds the code's boundary in the first place.
  assert.match(svg, new RegExp(`viewBox="0 0 ${qr.size + 8} ${qr.size + 8}"`),
    "the default quiet zone must be 4 modules on every side");
  assert.ok(!/aria-label="[^"]*[<>&]/.test(svg), "label must not carry raw markup characters");
});

test("the path draws exactly the dark modules, merged into horizontal runs", () => {
  // Runs rather than individual squares: separately-drawn adjacent modules can
  // leave hairline seams once crispEdges snaps them to device pixels, and white
  // lines through the dark blocks stop a detector locking on. This re-derives
  // the expected runs independently and checks both the count and the total
  // area, so a merge that dropped or doubled a module would fail.
  for (const sample of SAMPLES) {
    const qr = cwQr.matrix(sample);
    const svg = cwQr.svg(sample);
    let expectedRuns = 0, expectedDark = 0;
    for (let r = 0; r < qr.size; r++) {
      let c = 0;
      while (c < qr.size) {
        if (!qr.modules[r][c]) { c++; continue; }
        let len = 1;
        while (c + len < qr.size && qr.modules[r][c + len]) len++;
        expectedRuns++; expectedDark += len; c += len;
      }
    }
    const drawn = [...svg.matchAll(/M\d+ \d+h(\d+)v1h-\d+z/g)].map(m => Number(m[1]));
    assert.equal(drawn.length, expectedRuns, `${sample.slice(0, 20)}: wrong number of runs`);
    assert.equal(drawn.reduce((a, b) => a + b, 0), expectedDark, `${sample.slice(0, 20)}: runs don't cover the dark modules`);
    assert.equal(expectedDark, qr.modules.flat().filter(Boolean).length);
    // Every run must close back over its own width, or the fill is malformed.
    for (const m of svg.matchAll(/h(\d+)v1h-(\d+)z/g)) assert.equal(m[1], m[2], "a run must close over its own width");
  }
});

test("foreground and background colours are honoured", () => {
  const svg = cwQr.svg("CW1:A-001:123456", { fg: "#101010", bg: "#fafafa" });
  assert.ok(svg.includes('fill="#fafafa"'), "background colour missing");
  assert.ok(svg.includes('fill="#101010"'), "foreground colour missing");
});

console.log(failures ? `\n${failures} test(s) FAILED` : "\nall QR tests passed");
process.exit(failures ? 1 : 0);
